baseURL = "https://ionizing.page/"
languageCode = "zh-cn"
title = "伪化生搬砖工地"
theme = "maupassant"

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true
googleAnalytics = "UA-101595379-1"

hasCJKLanguage = true
summaryLength = 140

[author]
    name = "Ionizing"

[params]
    author = "Ionizing"
    subtitle = "Challenge Everything"
    keywords = "Programming,C,Rust,VASP,FirstPrinciple"
    description = "垃圾学校的延迟就业混子"
    busuanzi = true
    localSearch = true
    toc = true

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
    [markup.highlight]
        lineNos = true
        style = "github"

[params.utteranc]
    enable = true
    repo = "Ionizing/ionizing.github.io"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[params.sequenceDiagrams]
    enable = true
    options = "{theme: 'simple'}"            # default: "{theme: 'simple'}"

[params.flowchartDiagrams]
    enable = true
    # options = ""
